.PHONY: rnumbers, rwalk, diffusion, gases, clean

Part := 1,2

rnumbers:
	python3 rnumbers.py --part=${Part}

rwalk:
	python3 rwalk.py --part=${Part}

diffusion:
	python3 diffusion.py

gases:
	python3 gases.py --part=${Part}

clean:
	rm -r *.jpeg
        
